name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Ruff Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          uv sync --extra dev

      - name: Ruff check
        run: |
          uv run ruff check .

      - name: Ruff format check
        run: |
          uv run ruff format --check .

  test:
    name: Pytest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          uv sync --extra dev

      - name: Run tests
        env:
          OPENAI_API_KEY: 'test-key'
        run: |
          uv run pytest
